[package]
name = "kompact_benchmarks"
version = "0.1.0"
authors = ["Lars Kroll <lkroll@kth.se>"]
edition = '2018'

[dependencies]
kompact = { path = "../../kompics-rust/core/" }
benchmark_suite_shared = { path = "../shared_rust/" }
protobuf        = "2"
futures         = "0.1"
futures-cpupool = "0.1"
grpc 			= "0.5"
synchronoise 	= "0.4"
slog 			= {version = "2.2", features = ["max_level_debug", "release_max_level_warn"]}
time 			= "0.1"
tokio-core 		= "0.1"
